### ISSUE TITLE
License status

### ISSUE THREAD

**Issue by Tortoise17** [thomas-bouvier/music-genre-recognition#1]
Dear Respected brother. 

Very nice great and excellent effort. This is the fastest implementation I have seen so far. 
May I ask what is the status of the license for this tool?

Greetings.

**Comment by thomas-bouvier** [comment]
Hi and thank for your feedback!

I updated the license, feel free to do whatever you want with the sources. Don't hesitate to propose a pull request in case you get better performance though 😉
