### ISSUE TITLE
Multiple files 

### ISSUE THREAD

**Issue by Tortoise17** [thomas-bouvier/music-genre-recognition#2]
Dear Respected Colleague. 

Thank you so much for kind help of license. Really your effort impressed me a lot. Specially, your IO is very robust.
I would like to ask one more point, if it is possible to load multiple files for testing in one GO! or one time? or if there is series of files available in one folder, then like starting from a* and testing all files with A series or all files in same folder? Normally, I never tried multiple files with tensorflow model so I don't know how to handle this. it would be Great help

Greetings.

**Comment by ghost** [comment]
Hi,

I've updated the code so that you can now specify a folder for the testing mode, see 3ec0d18.
Simply use -folder <folder_name> instead of -song <song_file>. 
The readme has also been updated and give more information.
